import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
const require=createRequire(import.meta.url);
let ts;
try { ts=require('typescript'); } catch { ts=require(require('node:path').join(execFileSync('npm',['root','-g'],{encoding:'utf8'}).trim(),'typescript')); }
const read=(p)=>readFileSync(p,'utf8');
const page=read('src/app/dashboard/obstetra/page.tsx');
const nav=read('src/data/navigation.ts');
const pkg=JSON.parse(read('package.json'));
const sf=ts.createSourceFile('obstetra/page.tsx',page,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);
assert.equal(sf.parseDiagnostics.length,0, sf.parseDiagnostics.map(d=>d.messageText).join('; '));
assert(nav.includes('{ label: "Acompanhamento", href: "/dashboard/obstetra", icon: Baby }'));
assert(!nav.includes('{ label: "Obstetra", href: "/dashboard/obstetra", icon: Baby }'));
assert(page.includes('Acompanhamento gestacional'));
assert(page.includes('Fertilização in vitro'));
assert(page.includes('Vacinação gestacional'));
assert(page.includes('workspaceView === "vaccination"'));
assert(page.includes('workspaceView === "planning"'));
assert(!page.includes('Escolha o contexto de trabalho. A página adapta as ferramentas'));
assert(!page.includes('aria-label="Acesso rápido ao planejamento"'));
assert(!page.includes('scrollToPlanningSection'));
assert(page.includes('role={error ? "alert" : "status"}'));
assert(page.includes('z-[260]'));
assert(page.includes('busy ? "Salvando..."'));
assert(page.includes('await Promise.all(removable.map'));
assert(page.includes('await Promise.all(steps.map'));
assert(page.includes('await Promise.all([loadHistory(planId), loadOccurrences(planId)])'));
assert(page.includes('await Promise.all([loadHistory(selectedPlan.id), loadOccurrences(selectedPlan.id)])'));
assert(!page.includes('Pediatria'));
assert.equal(pkg.version,'1.1.16-test.30');
assert.equal(pkg.packageManager,'pnpm@12.2.0');
assert(read('src/components/layout/DeveloperCreditsModal.tsx').includes('systemVersion = "1.1.16-test.30"'));
console.log('PASS v1.1.14: feedback e otimizações da v1.1.13 preservados; navegação redundante removida');
