import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const read=(p)=>readFileSync(p,'utf8');
const page=read('src/app/dashboard/vacinacao/page.tsx');
const shared=read('src/components/vaccination/VaccinationWorkspace.tsx');
const obstetra=read('src/app/dashboard/obstetra/page.tsx');
const sql=read('supabase/migrations/20261004180000_gestational_vaccination_obstetra_v118.sql');
assert(page.includes('mode="regular"'));
assert(!page.includes('selectVaccinationModel("gestante")'));
assert(shared.includes('mode === "regular" && <section'));
assert(shared.includes('setGroup("gestante")'));
assert(shared.includes('mode === "gestational" ? item.group === "gestante" : item.group !== "gestante"'));
assert(shared.includes('card.card_model === "gestante" : card.card_model !== "gestante"'));
assert(obstetra.includes('<VaccinationWorkspace mode="gestational" />'));
assert(sql.includes('AS RESTRICTIVE FOR SELECT'));
assert(sql.includes('BEFORE INSERT OR UPDATE OR DELETE'));
assert(sql.includes("access_status='Aprovado'"));
assert(read('src/app/api/paciente/registros/route.ts').includes('Caderneta de vacinação gestacional'));
assert.equal(JSON.parse(read('package.json')).version,'1.1.16-test.30');
const access = read('src/lib/gestational-vaccination-access.ts');
assert(access.includes('isFullAccessAdministrativeRole(normalizedRole)'));
const adminMigration = read('supabase/migrations/20261005050658_v112_restore_full_admin_access.sql');
assert(adminMigration.includes('hpsr_can_manage_gestational_vaccination'));
assert(adminMigration.includes("p.role in ('Diretora', 'Vice Diretor / Dev')"));
console.log('PASS vacinação gestacional: Diretora/Vice Diretor Dev têm acesso administrativo total; demais perfis seguem especialidade');
