"use client";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, CheckCircle2, Clock3, Loader2, RefreshCcw, Stethoscope } from "lucide-react";

type Slot = { id:string; doctor_name:string; specialty:string; starts_at:string; ends_at:string; status:string };
export function PatientBookingPanel({ onSessionExpired, onBooked }: { onSessionExpired?:()=>void; onBooked?:()=>void }) {
  const [slots,setSlots]=useState<Slot[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [selected,setSelected]=useState<string>(""); const [patientName,setPatientName]=useState(""); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const requestInFlightRef=useRef<Promise<void>|null>(null); const lastLoadedAtRef=useRef(0); const onSessionExpiredRef=useRef(onSessionExpired); const onBookedRef=useRef(onBooked);
  useEffect(()=>{onSessionExpiredRef.current=onSessionExpired},[onSessionExpired]);
  useEffect(()=>{onBookedRef.current=onBooked},[onBooked]);
  const load=useCallback(async(force=false)=>{
    if(!force && Date.now()-lastLoadedAtRef.current<15000)return;
    if(requestInFlightRef.current)return requestInFlightRef.current;
    const request=(async()=>{setLoading(true);setError("");try{const r=await fetch('/api/paciente/horarios',{cache:'no-store'});const d=await r.json();if(r.status===401){onSessionExpiredRef.current?.();return;}if(!r.ok||!d.ok)throw new Error(d.error||'Falha ao carregar horários.');setSlots(d.slots||[]);setPatientName(String(d.patientName||''));lastLoadedAtRef.current=Date.now();}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar horários.');}finally{setLoading(false)}})();
    requestInFlightRef.current=request; try{await request}finally{requestInFlightRef.current=null}
  },[]);
  useEffect(()=>{void load(true)},[load]);
  const grouped=useMemo(()=>slots.reduce<Record<string,Slot[]>>((acc,s)=>{const key=new Date(s.starts_at).toLocaleDateString('pt-BR',{timeZone:'America/Sao_Paulo',weekday:'long',day:'2-digit',month:'long'});(acc[key]??=[]).push(s);return acc},{}),[slots]);
  async function book(){setSaving(true);setError("");setMessage("");try{const r=await fetch('/api/paciente/reservar-horario',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({slotId:selected,patientName})});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Não foi possível confirmar.');setMessage('Consulta confirmada com sucesso.');setSelected('');await load(true);onBookedRef.current?.();}catch(e){setError(e instanceof Error?e.message:'Não foi possível confirmar.');await load(true);}finally{setSaving(false)}}
  return <section className="rounded-[22px] border border-hpsr-border bg-white/95 p-4 sm:p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-hpsr-wineLight">Agendamento</p><h3 className="text-xl font-black text-hpsr-text">Escolha um horário</h3><p className="mt-1 text-sm font-semibold text-hpsr-muted">Os horários aparecem à meia-noite do dia anterior e permanecem disponíveis até o início do dia da consulta.</p></div><button onClick={()=>void load(true)} className="inline-flex items-center gap-2 rounded-[12px] border border-hpsr-border bg-white px-3 py-2 text-xs font-black text-hpsr-wine"><RefreshCcw size={14}/>Atualizar</button></div>
  <div className="mt-4 rounded-[14px] border border-hpsr-border bg-[#fffaf4] px-4 py-3 text-sm font-bold text-hpsr-text">Paciente: {patientName || "Identificado pela sessão"}</div>
  {loading?<div className="py-10 text-center"><Loader2 className="mx-auto animate-spin text-hpsr-wine"/></div>:!slots.length?<div className="mt-4 rounded-[16px] border border-dashed border-hpsr-border bg-[#fffaf4] p-6 text-center"><CalendarDays className="mx-auto text-hpsr-wine"/><p className="mt-2 font-black text-hpsr-text">Nenhum horário disponível</p><p className="mt-1 text-sm text-hpsr-muted">Nenhuma consulta planejada está com a janela de confirmação aberta hoje.</p></div>:<div className="mt-4 space-y-4">{Object.entries(grouped).map(([day,items])=><div key={day}><h4 className="mb-2 capitalize text-sm font-black text-hpsr-text">{day}</h4><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{items.map(slot=>{const active=selected===slot.id;const time=new Date(slot.starts_at).toLocaleTimeString('pt-BR',{timeZone:'America/Sao_Paulo',hour:'2-digit',minute:'2-digit'});return <button key={slot.id} onClick={()=>setSelected(slot.id)} className={`rounded-[15px] border p-3 text-left transition ${active?'border-hpsr-wine bg-hpsr-wine text-white':'border-hpsr-border bg-[#fffaf4] text-hpsr-text hover:border-hpsr-wineLight'}`}><div className="flex items-center justify-between"><span className="text-base font-black">{time}</span><Clock3 size={16}/></div><p className={`mt-1 text-xs font-bold ${active?'text-white/85':'text-hpsr-muted'}`}><Stethoscope className="mr-1 inline" size={13}/>{slot.specialty}</p><p className={`mt-1 text-xs ${active?'text-white/80':'text-hpsr-muted'}`}>{slot.doctor_name}</p></button>})}</div></div>)}</div>}
  {message&&<p className="mt-4 rounded-[12px] border border-emerald-200 bg-emerald-50 px-3 py-2 text-sm font-bold text-emerald-800"><CheckCircle2 className="mr-2 inline" size={16}/>{message}</p>}{error&&<p className="mt-4 rounded-[12px] border border-rose-200 bg-rose-50 px-3 py-2 text-sm font-bold text-rose-800">{error}</p>}
  <button disabled={saving||!selected||!patientName.trim()} onClick={()=>void book()} className="mt-4 inline-flex min-h-[48px] w-full items-center justify-center gap-2 rounded-[14px] bg-hpsr-wine px-4 text-sm font-black text-white disabled:opacity-50">{saving?<Loader2 className="animate-spin" size={17}/>:<CheckCircle2 size={17}/>}Confirmar agendamento</button></section>;
}
